export const translations = {
  en: {
    title1: "One Platform.",
    title2: "For Every Farmer's Need.",
    desc: "Sell crops directly. Book tractors. Hire workers. Get government schemes.",
    btn1: "Get Started Free",
    btn2: "Explore Marketplace",
    badge: "Empowering farmers, end to end.",
    noMiddle: "No middlemen",
    free: "Free for farmers",
    marketplace: "Marketplace",
    tractor: "Tractor & Tools",
    labour: "Hire Labour",
    crop: "Crop Doctor",
    weather: "Weather",
    schemes: "Govt Schemes",
    login: "Login",
    signup: "Sign up",
    dashboard: "Dashboard",
    logout: "Logout",
    weatherTitle: "Weather Forecast & Crop Advisory",
    weatherDesc: "7-day forecast and smart advice tailored for your city.",
    searchPlaceholder: "Enter city...",
    today: "TODAY",
    humidity: "Humidity",
    wind: "Wind",
    rain: "Rain",
    nextDays: "Next 7 Days",
    cropAdvisory: "Crop Advisory",
    features: "Features",
    featuresTitle: "Everything a Farmer Needs",
    featuresDesc: "From selling crops to getting government aid — all in one place.",
    stats: "Trusted by Farmers",
    farmers: "Farmers",
    villages: "Villages",
    croresTraded: "Crores Traded",
    howTitle: "How Shetkari Mitra Works",
    howDesc: "Simple steps to get started",
    step1: "Create your account",
    step1Desc: "Register as Farmer, Labour, Tractor Owner or Government Official",
    step2: "Complete your profile",
    step2Desc: "Add your crops, equipment or skills to get discovered",
    step3: "Connect & Earn",
    step3Desc: "Start trading, hiring or accessing government schemes",
    testimonials: "What Farmers Say",
    ctaTitle: "Join 50,000+ farmers already on Shetkari Mitra",
    ctaBtn: "Start for Free Today",
    footer: "Empowering Maharashtra's farming community",
  },
  mr: {
    title1: "एक व्यासपीठ.",
    title2: "प्रत्येक शेतकऱ्याच्या गरजांसाठी.",
    desc: "पिके थेट विक्री करा. ट्रॅक्टर बुक करा. मजूर भाड्याने घ्या.",
    btn1: "सुरू करा",
    btn2: "मार्केटप्लेस पाहा",
    badge: "शेतकऱ्यांना सक्षम बनवत आहे",
    noMiddle: "मध्यस्थ नाहीत",
    free: "शेतकऱ्यांसाठी मोफत",
    marketplace: "मार्केटप्लेस",
    tractor: "ट्रॅक्टर व साधने",
    labour: "मजूर भाड्याने",
    crop: "पीक डॉक्टर",
    weather: "हवामान",
    schemes: "शासकीय योजना",
    login: "लॉगिन",
    signup: "साइन अप",
    dashboard: "डॅशबोर्ड",
    logout: "लॉगआउट",
    weatherTitle: "हवामान अंदाज व पीक सल्ला",
    weatherDesc: "आपल्या शहरासाठी ७ दिवसांचा हवामान अंदाज",
    searchPlaceholder: "शहर टाका...",
    today: "आज",
    humidity: "आर्द्रता",
    wind: "वारा",
    rain: "पाऊस",
    nextDays: "पुढील ७ दिवस",
    cropAdvisory: "पीक सल्ला",
    features: "वैशिष्ट्ये",
    featuresTitle: "शेतकऱ्यांसाठी सर्वकाही",
    featuresDesc: "पिके विकण्यापासून सरकारी मदत मिळवण्यापर्यंत",
    stats: "शेतकऱ्यांचा विश्वास",
    farmers: "शेतकरी",
    villages: "गावे",
    croresTraded: "कोटी व्यवहार",
    howTitle: "शेतकरी मित्र कसे काम करते",
    howDesc: "सुरू करण्यासाठी सोपे पावले",
    step1: "खाते तयार करा",
    step1Desc: "शेतकरी, मजूर, ट्रॅक्टर मालक किंवा सरकारी अधिकारी म्हणून नोंदणी करा",
    step2: "प्रोफाइल पूर्ण करा",
    step2Desc: "आपली पिके, उपकरणे किंवा कौशल्ये जोडा",
    step3: "जोडा आणि कमवा",
    step3Desc: "व्यापार, भाड्याने घेणे किंवा सरकारी योजनांचा लाभ घ्या",
    testimonials: "शेतकरी काय म्हणतात",
    ctaTitle: "५०,००० पेक्षा जास्त शेतकरी शेतकरी मित्रावर",
    ctaBtn: "आज मोफत सुरू करा",
    footer: "महाराष्ट्राच्या शेती समुदायाला सक्षम बनवत आहे",
  }
};
